input_sequence = input("Enter a comma-separated value of sequence of words : ")
words = set(input_sequence.split())
sorted_words = sorted(words)
result = ' '.join(sorted_words)
print("Result : ",result)